[package]
name = "mach-test"
version = "0.1.0"
authors = ["Yuki Okushi <huyuumi.dev@gmail.com>"]
build = "build.rs"
edition = "2021"

[dependencies]
mach2 = { path = ".." }

[build-dependencies]
ctest = "0.5.0"

[[test]]
name = "main"
path = "test/main.rs"
harness = false
