[package]
name = "mach-test"
version = "0.1.0"
authors = ["gnzlbg <gonzalobg88@gmail.com>"]
build = "build.rs"
edition = "2024"

[dependencies]
mach2 = { path = ".." }
libc = "0.2"

[build-dependencies]
ctest = "=0.5.0-beta.1"

[[test]]
name = "main"
path = "test/main.rs"
harness = false
